apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-services
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argproj.io
spec:
  project: default
  source:
    path: app
    repoURL: https://github.com/keszi000/test-env.git
    targetRevision: HEAD
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
