apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argproj.io
spec:
  project: default
  source:
    path: demoapp
    repoURL: https://github.com/keszi000/components.git
    targetRevision: HEAD
    helm:
      values: |
        replicaCount: 5
        image:
          tag: {{ .Values.demoapp.version }}
        ingress:
          enabled: true
          host: {{ .Values.demoapp.host }}
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
