apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argproj.io
spec:
  project: default
  source:
    path: nginx
    repoURL: https://github.com/keszi000/components.git
    targetRevision: HEAD
    helm:
      values: |
        replicaCount: 2
        image:
          tag: latest
        ingress:
          enabled: true
          host: nginx.127.0.0.1.xip.io
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
